4x tests due to pak not liking the CI environment.
Error: Error: ! error in pak subprocess
Caused by error in `get_user_cache_dir()`:
! R_USER_CACHE_DIR env var not set during package check, see https://github.com/r-lib/pkgcache#README